// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(sudachi_swiftFFI)
import sudachi_swiftFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_sudachi_swift_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_sudachi_swift_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureSudachiSwiftInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt32: FfiConverterPrimitive {
    typealias FfiType = Int32
    typealias SwiftType = Int32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int32, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




/**
 * Japanese morphological analyzer powered by sudachi.rs
 */
public protocol TokenizerProtocol: AnyObject, Sendable {
    
    /**
     * Tokenize text and return morpheme information
     */
    func tokenize(text: String, mode: TokenizeMode) throws  -> [MorphemeInfo]
    
    /**
     * Get the wrapper version
     */
    func version()  -> String
    
}
/**
 * Japanese morphological analyzer powered by sudachi.rs
 */
open class Tokenizer: TokenizerProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_sudachi_swift_fn_clone_tokenizer(self.handle, $0) }
    }
    /**
     * Create a new tokenizer with the given configuration
     */
public convenience init(config: TokenizerConfig)throws  {
    let handle =
        try rustCallWithError(FfiConverterTypeSudachiError_lift) {
    uniffi_sudachi_swift_fn_constructor_tokenizer_new(
        FfiConverterTypeTokenizerConfig_lower(config),$0
    )
}
    self.init(unsafeFromHandle: handle)
}

    deinit {
        try! rustCall { uniffi_sudachi_swift_fn_free_tokenizer(handle, $0) }
    }

    
    /**
     * Create a tokenizer with just a dictionary path (no config file)
     */
public static func withDictionary(dictionaryPath: String)throws  -> Tokenizer  {
    return try  FfiConverterTypeTokenizer_lift(try rustCallWithError(FfiConverterTypeSudachiError_lift) {
    uniffi_sudachi_swift_fn_constructor_tokenizer_with_dictionary(
        FfiConverterString.lower(dictionaryPath),$0
    )
})
}
    

    
    /**
     * Tokenize text and return morpheme information
     */
open func tokenize(text: String, mode: TokenizeMode)throws  -> [MorphemeInfo]  {
    return try  FfiConverterSequenceTypeMorphemeInfo.lift(try rustCallWithError(FfiConverterTypeSudachiError_lift) {
    uniffi_sudachi_swift_fn_method_tokenizer_tokenize(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(text),
        FfiConverterTypeTokenizeMode_lower(mode),$0
    )
})
}
    
    /**
     * Get the wrapper version
     */
open func version() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_sudachi_swift_fn_method_tokenizer_version(
            self.uniffiCloneHandle(),$0
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeTokenizer: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = Tokenizer

    public static func lift(_ handle: UInt64) throws -> Tokenizer {
        return Tokenizer(unsafeFromHandle: handle)
    }

    public static func lower(_ value: Tokenizer) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Tokenizer {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: Tokenizer, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTokenizer_lift(_ handle: UInt64) throws -> Tokenizer {
    return try FfiConverterTypeTokenizer.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTokenizer_lower(_ value: Tokenizer) -> UInt64 {
    return FfiConverterTypeTokenizer.lower(value)
}




/**
 * Get information about a dictionary type
 */
public struct DictionaryInfo: Equatable, Hashable {
    /**
     * Dictionary type name
     */
    public var name: String
    /**
     * Approximate size in MB
     */
    public var sizeMb: UInt32
    /**
     * Description
     */
    public var description: String
    /**
     * Download URL
     */
    public var downloadUrl: String
    /**
     * Filename inside the zip (e.g., "system_core.dic")
     */
    public var dicFilename: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Dictionary type name
         */name: String, 
        /**
         * Approximate size in MB
         */sizeMb: UInt32, 
        /**
         * Description
         */description: String, 
        /**
         * Download URL
         */downloadUrl: String, 
        /**
         * Filename inside the zip (e.g., "system_core.dic")
         */dicFilename: String) {
        self.name = name
        self.sizeMb = sizeMb
        self.description = description
        self.downloadUrl = downloadUrl
        self.dicFilename = dicFilename
    }

    
}

#if compiler(>=6)
extension DictionaryInfo: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDictionaryInfo: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DictionaryInfo {
        return
            try DictionaryInfo(
                name: FfiConverterString.read(from: &buf), 
                sizeMb: FfiConverterUInt32.read(from: &buf), 
                description: FfiConverterString.read(from: &buf), 
                downloadUrl: FfiConverterString.read(from: &buf), 
                dicFilename: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: DictionaryInfo, into buf: inout [UInt8]) {
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterUInt32.write(value.sizeMb, into: &buf)
        FfiConverterString.write(value.description, into: &buf)
        FfiConverterString.write(value.downloadUrl, into: &buf)
        FfiConverterString.write(value.dicFilename, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDictionaryInfo_lift(_ buf: RustBuffer) throws -> DictionaryInfo {
    return try FfiConverterTypeDictionaryInfo.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDictionaryInfo_lower(_ value: DictionaryInfo) -> RustBuffer {
    return FfiConverterTypeDictionaryInfo.lower(value)
}


/**
 * Information about a single morpheme (token)
 */
public struct MorphemeInfo: Equatable, Hashable {
    /**
     * Surface form (original text as it appears)
     */
    public var surface: String
    /**
     * Part-of-speech tags (hierarchical, up to 6 levels)
     */
    public var partOfSpeech: [String]
    /**
     * Dictionary form (lemma)
     */
    public var dictionaryForm: String
    /**
     * Normalized form
     */
    public var normalizedForm: String
    /**
     * Reading form in katakana
     */
    public var readingForm: String
    /**
     * Whether this is an out-of-vocabulary word
     */
    public var isOov: Bool
    /**
     * Word ID in dictionary (-1 for OOV)
     */
    public var wordId: Int32
    /**
     * Start byte offset in original text
     */
    public var begin: UInt32
    /**
     * End byte offset in original text
     */
    public var end: UInt32

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Surface form (original text as it appears)
         */surface: String, 
        /**
         * Part-of-speech tags (hierarchical, up to 6 levels)
         */partOfSpeech: [String], 
        /**
         * Dictionary form (lemma)
         */dictionaryForm: String, 
        /**
         * Normalized form
         */normalizedForm: String, 
        /**
         * Reading form in katakana
         */readingForm: String, 
        /**
         * Whether this is an out-of-vocabulary word
         */isOov: Bool, 
        /**
         * Word ID in dictionary (-1 for OOV)
         */wordId: Int32, 
        /**
         * Start byte offset in original text
         */begin: UInt32, 
        /**
         * End byte offset in original text
         */end: UInt32) {
        self.surface = surface
        self.partOfSpeech = partOfSpeech
        self.dictionaryForm = dictionaryForm
        self.normalizedForm = normalizedForm
        self.readingForm = readingForm
        self.isOov = isOov
        self.wordId = wordId
        self.begin = begin
        self.end = end
    }

    
}

#if compiler(>=6)
extension MorphemeInfo: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMorphemeInfo: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MorphemeInfo {
        return
            try MorphemeInfo(
                surface: FfiConverterString.read(from: &buf), 
                partOfSpeech: FfiConverterSequenceString.read(from: &buf), 
                dictionaryForm: FfiConverterString.read(from: &buf), 
                normalizedForm: FfiConverterString.read(from: &buf), 
                readingForm: FfiConverterString.read(from: &buf), 
                isOov: FfiConverterBool.read(from: &buf), 
                wordId: FfiConverterInt32.read(from: &buf), 
                begin: FfiConverterUInt32.read(from: &buf), 
                end: FfiConverterUInt32.read(from: &buf)
        )
    }

    public static func write(_ value: MorphemeInfo, into buf: inout [UInt8]) {
        FfiConverterString.write(value.surface, into: &buf)
        FfiConverterSequenceString.write(value.partOfSpeech, into: &buf)
        FfiConverterString.write(value.dictionaryForm, into: &buf)
        FfiConverterString.write(value.normalizedForm, into: &buf)
        FfiConverterString.write(value.readingForm, into: &buf)
        FfiConverterBool.write(value.isOov, into: &buf)
        FfiConverterInt32.write(value.wordId, into: &buf)
        FfiConverterUInt32.write(value.begin, into: &buf)
        FfiConverterUInt32.write(value.end, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMorphemeInfo_lift(_ buf: RustBuffer) throws -> MorphemeInfo {
    return try FfiConverterTypeMorphemeInfo.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMorphemeInfo_lower(_ value: MorphemeInfo) -> RustBuffer {
    return FfiConverterTypeMorphemeInfo.lower(value)
}


/**
 * Configuration for creating a Tokenizer
 */
public struct TokenizerConfig: Equatable, Hashable {
    /**
     * Path to the system dictionary file (.dic)
     */
    public var dictionaryPath: String
    /**
     * Optional path to sudachi.json config file
     */
    public var configPath: String?
    /**
     * Optional path to resource directory (where char.def, unk.def are located)
     * If not provided, will use the parent directory of config_path or dictionary_path
     */
    public var resourcePath: String?
    /**
     * Optional path to user dictionary file
     */
    public var userDictionaryPath: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Path to the system dictionary file (.dic)
         */dictionaryPath: String, 
        /**
         * Optional path to sudachi.json config file
         */configPath: String?, 
        /**
         * Optional path to resource directory (where char.def, unk.def are located)
         * If not provided, will use the parent directory of config_path or dictionary_path
         */resourcePath: String?, 
        /**
         * Optional path to user dictionary file
         */userDictionaryPath: String?) {
        self.dictionaryPath = dictionaryPath
        self.configPath = configPath
        self.resourcePath = resourcePath
        self.userDictionaryPath = userDictionaryPath
    }

    
}

#if compiler(>=6)
extension TokenizerConfig: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeTokenizerConfig: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> TokenizerConfig {
        return
            try TokenizerConfig(
                dictionaryPath: FfiConverterString.read(from: &buf), 
                configPath: FfiConverterOptionString.read(from: &buf), 
                resourcePath: FfiConverterOptionString.read(from: &buf), 
                userDictionaryPath: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: TokenizerConfig, into buf: inout [UInt8]) {
        FfiConverterString.write(value.dictionaryPath, into: &buf)
        FfiConverterOptionString.write(value.configPath, into: &buf)
        FfiConverterOptionString.write(value.resourcePath, into: &buf)
        FfiConverterOptionString.write(value.userDictionaryPath, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTokenizerConfig_lift(_ buf: RustBuffer) throws -> TokenizerConfig {
    return try FfiConverterTypeTokenizerConfig.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTokenizerConfig_lower(_ value: TokenizerConfig) -> RustBuffer {
    return FfiConverterTypeTokenizerConfig.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Type of Sudachi dictionary
 */

public enum DictionaryType: Equatable, Hashable {
    
    /**
     * Small dictionary (~50MB) - minimum vocabulary
     */
    case small
    /**
     * Core dictionary (~70MB) - basic vocabulary (recommended)
     */
    case core
    /**
     * Full dictionary (~1GB) - complete vocabulary
     */
    case full



}

#if compiler(>=6)
extension DictionaryType: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDictionaryType: FfiConverterRustBuffer {
    typealias SwiftType = DictionaryType

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DictionaryType {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .small
        
        case 2: return .core
        
        case 3: return .full
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: DictionaryType, into buf: inout [UInt8]) {
        switch value {
        
        
        case .small:
            writeInt(&buf, Int32(1))
        
        
        case .core:
            writeInt(&buf, Int32(2))
        
        
        case .full:
            writeInt(&buf, Int32(3))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDictionaryType_lift(_ buf: RustBuffer) throws -> DictionaryType {
    return try FfiConverterTypeDictionaryType.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDictionaryType_lower(_ value: DictionaryType) -> RustBuffer {
    return FfiConverterTypeDictionaryType.lower(value)
}



public enum SudachiError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    case DictionaryLoadError(message: String
    )
    case ConfigError(message: String
    )
    case TokenizeError(message: String
    )
    case InvalidArgument(message: String
    )

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension SudachiError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSudachiError: FfiConverterRustBuffer {
    typealias SwiftType = SudachiError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SudachiError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .DictionaryLoadError(
            message: try FfiConverterString.read(from: &buf)
            )
        case 2: return .ConfigError(
            message: try FfiConverterString.read(from: &buf)
            )
        case 3: return .TokenizeError(
            message: try FfiConverterString.read(from: &buf)
            )
        case 4: return .InvalidArgument(
            message: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: SudachiError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .DictionaryLoadError(message):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .ConfigError(message):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .TokenizeError(message):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .InvalidArgument(message):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(message, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSudachiError_lift(_ buf: RustBuffer) throws -> SudachiError {
    return try FfiConverterTypeSudachiError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSudachiError_lower(_ value: SudachiError) -> RustBuffer {
    return FfiConverterTypeSudachiError.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Tokenization granularity mode
 */

public enum TokenizeMode: Equatable, Hashable {
    
    /**
     * Short unit mode - maximum segmentation (equivalent to UniDic short unit)
     */
    case a
    /**
     * Middle unit mode - word-like segmentation
     */
    case b
    /**
     * Long unit mode - minimal segmentation, extracts named entities
     */
    case c



}

#if compiler(>=6)
extension TokenizeMode: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeTokenizeMode: FfiConverterRustBuffer {
    typealias SwiftType = TokenizeMode

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> TokenizeMode {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .a
        
        case 2: return .b
        
        case 3: return .c
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: TokenizeMode, into buf: inout [UInt8]) {
        switch value {
        
        
        case .a:
            writeInt(&buf, Int32(1))
        
        
        case .b:
            writeInt(&buf, Int32(2))
        
        
        case .c:
            writeInt(&buf, Int32(3))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTokenizeMode_lift(_ buf: RustBuffer) throws -> TokenizeMode {
    return try FfiConverterTypeTokenizeMode.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTokenizeMode_lower(_ value: TokenizeMode) -> RustBuffer {
    return FfiConverterTypeTokenizeMode.lower(value)
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeDictionaryInfo: FfiConverterRustBuffer {
    typealias SwiftType = [DictionaryInfo]

    public static func write(_ value: [DictionaryInfo], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeDictionaryInfo.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [DictionaryInfo] {
        let len: Int32 = try readInt(&buf)
        var seq = [DictionaryInfo]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeDictionaryInfo.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeMorphemeInfo: FfiConverterRustBuffer {
    typealias SwiftType = [MorphemeInfo]

    public static func write(_ value: [MorphemeInfo], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeMorphemeInfo.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [MorphemeInfo] {
        let len: Int32 = try readInt(&buf)
        var seq = [MorphemeInfo]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeMorphemeInfo.read(from: &buf))
        }
        return seq
    }
}
/**
 * Get all available dictionary types with their info
 */
public func getAllDictionaryInfo(version: String?) -> [DictionaryInfo]  {
    return try!  FfiConverterSequenceTypeDictionaryInfo.lift(try! rustCall() {
    uniffi_sudachi_swift_fn_func_get_all_dictionary_info(
        FfiConverterOptionString.lower(version),$0
    )
})
}
/**
 * Get the download URL for a specific dictionary type and version
 *
 * - `dict_type`: The type of dictionary (small, core, full)
 * - `version`: Optional version string (e.g., "20241021"). If None, uses "latest"
 *
 * Returns the URL to download the dictionary zip file
 */
public func getDictionaryDownloadUrl(dictType: DictionaryType, version: String?) -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_sudachi_swift_fn_func_get_dictionary_download_url(
        FfiConverterTypeDictionaryType_lower(dictType),
        FfiConverterOptionString.lower(version),$0
    )
})
}
/**
 * Get information about available dictionaries
 */
public func getDictionaryInfo(dictType: DictionaryType, version: String?) -> DictionaryInfo  {
    return try!  FfiConverterTypeDictionaryInfo_lift(try! rustCall() {
    uniffi_sudachi_swift_fn_func_get_dictionary_info(
        FfiConverterTypeDictionaryType_lower(dictType),
        FfiConverterOptionString.lower(version),$0
    )
})
}
/**
 * Get the library version
 */
public func getVersion() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_sudachi_swift_fn_func_get_version($0
    )
})
}
/**
 * Quick tokenization without creating a persistent Tokenizer object
 *
 * This is useful for one-off tokenization but less efficient for repeated use.
 * For multiple tokenizations, create a Tokenizer instance and reuse it.
 */
public func tokenizeText(text: String, dictionaryPath: String, mode: TokenizeMode)throws  -> [MorphemeInfo]  {
    return try  FfiConverterSequenceTypeMorphemeInfo.lift(try rustCallWithError(FfiConverterTypeSudachiError_lift) {
    uniffi_sudachi_swift_fn_func_tokenize_text(
        FfiConverterString.lower(text),
        FfiConverterString.lower(dictionaryPath),
        FfiConverterTypeTokenizeMode_lower(mode),$0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_sudachi_swift_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_sudachi_swift_checksum_func_get_all_dictionary_info() != 829) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_sudachi_swift_checksum_func_get_dictionary_download_url() != 4096) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_sudachi_swift_checksum_func_get_dictionary_info() != 64751) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_sudachi_swift_checksum_func_get_version() != 831) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_sudachi_swift_checksum_func_tokenize_text() != 35964) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_sudachi_swift_checksum_method_tokenizer_tokenize() != 35835) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_sudachi_swift_checksum_method_tokenizer_version() != 7532) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_sudachi_swift_checksum_constructor_tokenizer_new() != 15321) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_sudachi_swift_checksum_constructor_tokenizer_with_dictionary() != 55743) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureSudachiSwiftInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all