// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(sudachi_swiftFFI)
import sudachi_swiftFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_sudachi_swift_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_sudachi_swift_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureSudachiSwiftInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt32: FfiConverterPrimitive {
    typealias FfiType = Int32
    typealias SwiftType = Int32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int32, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




public protocol TokenizerProtocol: AnyObject, Sendable {
    
    /**
     * Look up dictionary entries whose surface matches `query` exactly.
     * Mirrors `Dictionary.lookup(surface)` in the Python binding.
     */
    func lookup(query: String) throws  -> [MorphemeInfo]
    
    /**
     * Resolve a part-of-speech ID to its hierarchical components.
     * Mirrors `Dictionary.pos_of(pos_id)` in the Python binding.
     */
    func posOf(posId: UInt32)  -> [String]?
    
    /**
     * Sentence-split `text` using this tokenizer's lexicon to avoid breaking
     * inside known multi-character expressions.
     */
    func splitSentences(text: String)  -> [SentenceRange]
    
    func tokenize(text: String, mode: TokenizeMode) throws  -> [MorphemeInfo]
    
    /**
     * Tokenize with `mode`, then split each morpheme into sub-units using
     * `sub_mode`. Typical use: C (long unit / named entities) with A (max
     * segmentation). Mirrors `Morpheme.split(mode, add_single)` in the
     * Python binding: when `add_single` is true, morphemes that cannot
     * split further get a single-element `subunits` containing themselves;
     * when false, those entries get an empty `subunits` vector.
     */
    func tokenizeWithSubunits(text: String, mode: TokenizeMode, subMode: TokenizeMode, addSingle: Bool) throws  -> [MorphemeWithSubunits]
    
}
open class Tokenizer: TokenizerProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_sudachi_swift_fn_clone_tokenizer(self.handle, $0) }
    }
public convenience init(config: TokenizerConfig)throws  {
    let handle =
        try rustCallWithError(FfiConverterTypeSudachiError_lift) {
    uniffi_sudachi_swift_fn_constructor_tokenizer_new(
        FfiConverterTypeTokenizerConfig_lower(config),$0
    )
}
    self.init(unsafeFromHandle: handle)
}

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_sudachi_swift_fn_free_tokenizer(handle, $0) }
    }

    
public static func withDictionary(dictionaryPath: String)throws  -> Tokenizer  {
    return try  FfiConverterTypeTokenizer_lift(try rustCallWithError(FfiConverterTypeSudachiError_lift) {
    uniffi_sudachi_swift_fn_constructor_tokenizer_with_dictionary(
        FfiConverterString.lower(dictionaryPath),$0
    )
})
}
    

    
    /**
     * Look up dictionary entries whose surface matches `query` exactly.
     * Mirrors `Dictionary.lookup(surface)` in the Python binding.
     */
open func lookup(query: String)throws  -> [MorphemeInfo]  {
    return try  FfiConverterSequenceTypeMorphemeInfo.lift(try rustCallWithError(FfiConverterTypeSudachiError_lift) {
    uniffi_sudachi_swift_fn_method_tokenizer_lookup(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(query),$0
    )
})
}
    
    /**
     * Resolve a part-of-speech ID to its hierarchical components.
     * Mirrors `Dictionary.pos_of(pos_id)` in the Python binding.
     */
open func posOf(posId: UInt32) -> [String]?  {
    return try!  FfiConverterOptionSequenceString.lift(try! rustCall() {
    uniffi_sudachi_swift_fn_method_tokenizer_pos_of(
            self.uniffiCloneHandle(),
        FfiConverterUInt32.lower(posId),$0
    )
})
}
    
    /**
     * Sentence-split `text` using this tokenizer's lexicon to avoid breaking
     * inside known multi-character expressions.
     */
open func splitSentences(text: String) -> [SentenceRange]  {
    return try!  FfiConverterSequenceTypeSentenceRange.lift(try! rustCall() {
    uniffi_sudachi_swift_fn_method_tokenizer_split_sentences(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(text),$0
    )
})
}
    
open func tokenize(text: String, mode: TokenizeMode)throws  -> [MorphemeInfo]  {
    return try  FfiConverterSequenceTypeMorphemeInfo.lift(try rustCallWithError(FfiConverterTypeSudachiError_lift) {
    uniffi_sudachi_swift_fn_method_tokenizer_tokenize(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(text),
        FfiConverterTypeTokenizeMode_lower(mode),$0
    )
})
}
    
    /**
     * Tokenize with `mode`, then split each morpheme into sub-units using
     * `sub_mode`. Typical use: C (long unit / named entities) with A (max
     * segmentation). Mirrors `Morpheme.split(mode, add_single)` in the
     * Python binding: when `add_single` is true, morphemes that cannot
     * split further get a single-element `subunits` containing themselves;
     * when false, those entries get an empty `subunits` vector.
     */
open func tokenizeWithSubunits(text: String, mode: TokenizeMode, subMode: TokenizeMode, addSingle: Bool)throws  -> [MorphemeWithSubunits]  {
    return try  FfiConverterSequenceTypeMorphemeWithSubunits.lift(try rustCallWithError(FfiConverterTypeSudachiError_lift) {
    uniffi_sudachi_swift_fn_method_tokenizer_tokenize_with_subunits(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(text),
        FfiConverterTypeTokenizeMode_lower(mode),
        FfiConverterTypeTokenizeMode_lower(subMode),
        FfiConverterBool.lower(addSingle),$0
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeTokenizer: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = Tokenizer

    public static func lift(_ handle: UInt64) throws -> Tokenizer {
        return Tokenizer(unsafeFromHandle: handle)
    }

    public static func lower(_ value: Tokenizer) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Tokenizer {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: Tokenizer, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTokenizer_lift(_ handle: UInt64) throws -> Tokenizer {
    return try FfiConverterTypeTokenizer.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTokenizer_lower(_ value: Tokenizer) -> UInt64 {
    return FfiConverterTypeTokenizer.lower(value)
}




/**
 * Information about a single morpheme (token)
 */
public struct MorphemeInfo: Equatable, Hashable {
    /**
     * Surface form (original text as it appears)
     */
    public var surface: String
    /**
     * Part-of-speech tags (hierarchical, up to 6 levels)
     */
    public var partOfSpeech: [String]
    /**
     * Dictionary form (lemma)
     */
    public var dictionaryForm: String
    /**
     * Normalized form
     */
    public var normalizedForm: String
    /**
     * Reading form in katakana
     */
    public var readingForm: String
    /**
     * Whether this is an out-of-vocabulary word
     */
    public var isOov: Bool
    /**
     * Encoded WordId (dictionary index packed with entry index). Mirrors
     * `Morpheme.word_id()` in the Python binding.
     */
    public var wordId: UInt32
    /**
     * Start UTF-8 byte offset in the original text. NOTE: Python's
     * `Morpheme.begin()` returns a codepoint offset — use `begin_char`
     * here for parity with sudachipy.
     */
    public var begin: UInt32
    /**
     * End UTF-8 byte offset in the original text. See note on `begin`.
     */
    public var end: UInt32
    /**
     * Part-of-speech numeric ID
     */
    public var partOfSpeechId: UInt32
    /**
     * Dictionary ID (-1 for system, 0+ for user dicts, -1 for OOV / unknown)
     */
    public var dictionaryId: Int32
    /**
     * Synonym group IDs this morpheme belongs to
     */
    public var synonymGroupIds: [UInt32]
    /**
     * Start Unicode codepoint offset in the original text (matches Python's
     * `Morpheme.begin()`).
     */
    public var beginChar: UInt32
    /**
     * End Unicode codepoint offset in the original text.
     */
    public var endChar: UInt32
    /**
     * Total cost of the path leading to this morpheme
     */
    public var totalCost: Int32

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Surface form (original text as it appears)
         */surface: String, 
        /**
         * Part-of-speech tags (hierarchical, up to 6 levels)
         */partOfSpeech: [String], 
        /**
         * Dictionary form (lemma)
         */dictionaryForm: String, 
        /**
         * Normalized form
         */normalizedForm: String, 
        /**
         * Reading form in katakana
         */readingForm: String, 
        /**
         * Whether this is an out-of-vocabulary word
         */isOov: Bool, 
        /**
         * Encoded WordId (dictionary index packed with entry index). Mirrors
         * `Morpheme.word_id()` in the Python binding.
         */wordId: UInt32, 
        /**
         * Start UTF-8 byte offset in the original text. NOTE: Python's
         * `Morpheme.begin()` returns a codepoint offset — use `begin_char`
         * here for parity with sudachipy.
         */begin: UInt32, 
        /**
         * End UTF-8 byte offset in the original text. See note on `begin`.
         */end: UInt32, 
        /**
         * Part-of-speech numeric ID
         */partOfSpeechId: UInt32, 
        /**
         * Dictionary ID (-1 for system, 0+ for user dicts, -1 for OOV / unknown)
         */dictionaryId: Int32, 
        /**
         * Synonym group IDs this morpheme belongs to
         */synonymGroupIds: [UInt32], 
        /**
         * Start Unicode codepoint offset in the original text (matches Python's
         * `Morpheme.begin()`).
         */beginChar: UInt32, 
        /**
         * End Unicode codepoint offset in the original text.
         */endChar: UInt32, 
        /**
         * Total cost of the path leading to this morpheme
         */totalCost: Int32) {
        self.surface = surface
        self.partOfSpeech = partOfSpeech
        self.dictionaryForm = dictionaryForm
        self.normalizedForm = normalizedForm
        self.readingForm = readingForm
        self.isOov = isOov
        self.wordId = wordId
        self.begin = begin
        self.end = end
        self.partOfSpeechId = partOfSpeechId
        self.dictionaryId = dictionaryId
        self.synonymGroupIds = synonymGroupIds
        self.beginChar = beginChar
        self.endChar = endChar
        self.totalCost = totalCost
    }

    

    
}

#if compiler(>=6)
extension MorphemeInfo: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMorphemeInfo: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MorphemeInfo {
        return
            try MorphemeInfo(
                surface: FfiConverterString.read(from: &buf), 
                partOfSpeech: FfiConverterSequenceString.read(from: &buf), 
                dictionaryForm: FfiConverterString.read(from: &buf), 
                normalizedForm: FfiConverterString.read(from: &buf), 
                readingForm: FfiConverterString.read(from: &buf), 
                isOov: FfiConverterBool.read(from: &buf), 
                wordId: FfiConverterUInt32.read(from: &buf), 
                begin: FfiConverterUInt32.read(from: &buf), 
                end: FfiConverterUInt32.read(from: &buf), 
                partOfSpeechId: FfiConverterUInt32.read(from: &buf), 
                dictionaryId: FfiConverterInt32.read(from: &buf), 
                synonymGroupIds: FfiConverterSequenceUInt32.read(from: &buf), 
                beginChar: FfiConverterUInt32.read(from: &buf), 
                endChar: FfiConverterUInt32.read(from: &buf), 
                totalCost: FfiConverterInt32.read(from: &buf)
        )
    }

    public static func write(_ value: MorphemeInfo, into buf: inout [UInt8]) {
        FfiConverterString.write(value.surface, into: &buf)
        FfiConverterSequenceString.write(value.partOfSpeech, into: &buf)
        FfiConverterString.write(value.dictionaryForm, into: &buf)
        FfiConverterString.write(value.normalizedForm, into: &buf)
        FfiConverterString.write(value.readingForm, into: &buf)
        FfiConverterBool.write(value.isOov, into: &buf)
        FfiConverterUInt32.write(value.wordId, into: &buf)
        FfiConverterUInt32.write(value.begin, into: &buf)
        FfiConverterUInt32.write(value.end, into: &buf)
        FfiConverterUInt32.write(value.partOfSpeechId, into: &buf)
        FfiConverterInt32.write(value.dictionaryId, into: &buf)
        FfiConverterSequenceUInt32.write(value.synonymGroupIds, into: &buf)
        FfiConverterUInt32.write(value.beginChar, into: &buf)
        FfiConverterUInt32.write(value.endChar, into: &buf)
        FfiConverterInt32.write(value.totalCost, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMorphemeInfo_lift(_ buf: RustBuffer) throws -> MorphemeInfo {
    return try FfiConverterTypeMorphemeInfo.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMorphemeInfo_lower(_ value: MorphemeInfo) -> RustBuffer {
    return FfiConverterTypeMorphemeInfo.lower(value)
}


/**
 * A morpheme together with its sub-unit decomposition.
 */
public struct MorphemeWithSubunits: Equatable, Hashable {
    /**
     * The primary morpheme (e.g. from C mode).
     */
    public var morpheme: MorphemeInfo
    /**
     * Sub-unit decomposition (e.g. from A mode). If the morpheme cannot be
     * split further, this contains exactly one element equal to `morpheme`.
     */
    public var subunits: [MorphemeInfo]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * The primary morpheme (e.g. from C mode).
         */morpheme: MorphemeInfo, 
        /**
         * Sub-unit decomposition (e.g. from A mode). If the morpheme cannot be
         * split further, this contains exactly one element equal to `morpheme`.
         */subunits: [MorphemeInfo]) {
        self.morpheme = morpheme
        self.subunits = subunits
    }

    

    
}

#if compiler(>=6)
extension MorphemeWithSubunits: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMorphemeWithSubunits: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MorphemeWithSubunits {
        return
            try MorphemeWithSubunits(
                morpheme: FfiConverterTypeMorphemeInfo.read(from: &buf), 
                subunits: FfiConverterSequenceTypeMorphemeInfo.read(from: &buf)
        )
    }

    public static func write(_ value: MorphemeWithSubunits, into buf: inout [UInt8]) {
        FfiConverterTypeMorphemeInfo.write(value.morpheme, into: &buf)
        FfiConverterSequenceTypeMorphemeInfo.write(value.subunits, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMorphemeWithSubunits_lift(_ buf: RustBuffer) throws -> MorphemeWithSubunits {
    return try FfiConverterTypeMorphemeWithSubunits.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMorphemeWithSubunits_lower(_ value: MorphemeWithSubunits) -> RustBuffer {
    return FfiConverterTypeMorphemeWithSubunits.lower(value)
}


/**
 * A sentence range produced by the sentence splitter.
 */
public struct SentenceRange: Equatable, Hashable {
    /**
     * Byte offset begin in original text
     */
    public var begin: UInt32
    /**
     * Byte offset end in original text
     */
    public var end: UInt32
    /**
     * Sentence text (slice of original)
     */
    public var text: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Byte offset begin in original text
         */begin: UInt32, 
        /**
         * Byte offset end in original text
         */end: UInt32, 
        /**
         * Sentence text (slice of original)
         */text: String) {
        self.begin = begin
        self.end = end
        self.text = text
    }

    

    
}

#if compiler(>=6)
extension SentenceRange: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSentenceRange: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SentenceRange {
        return
            try SentenceRange(
                begin: FfiConverterUInt32.read(from: &buf), 
                end: FfiConverterUInt32.read(from: &buf), 
                text: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: SentenceRange, into buf: inout [UInt8]) {
        FfiConverterUInt32.write(value.begin, into: &buf)
        FfiConverterUInt32.write(value.end, into: &buf)
        FfiConverterString.write(value.text, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSentenceRange_lift(_ buf: RustBuffer) throws -> SentenceRange {
    return try FfiConverterTypeSentenceRange.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSentenceRange_lower(_ value: SentenceRange) -> RustBuffer {
    return FfiConverterTypeSentenceRange.lower(value)
}


/**
 * Configuration for creating a Tokenizer
 */
public struct TokenizerConfig: Equatable, Hashable {
    /**
     * Path to the system dictionary file (.dic)
     */
    public var dictionaryPath: String
    /**
     * Optional path to sudachi.json config file
     */
    public var configPath: String?
    /**
     * Optional path to resource directory (where char.def, unk.def are located)
     * If not provided, will use the parent directory of config_path or dictionary_path
     */
    public var resourcePath: String?
    /**
     * User dictionary files, applied in order. Mirrors the `userDict` array
     * in `sudachi.json`.
     */
    public var userDictionaryPaths: [String]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Path to the system dictionary file (.dic)
         */dictionaryPath: String, 
        /**
         * Optional path to sudachi.json config file
         */configPath: String?, 
        /**
         * Optional path to resource directory (where char.def, unk.def are located)
         * If not provided, will use the parent directory of config_path or dictionary_path
         */resourcePath: String?, 
        /**
         * User dictionary files, applied in order. Mirrors the `userDict` array
         * in `sudachi.json`.
         */userDictionaryPaths: [String]) {
        self.dictionaryPath = dictionaryPath
        self.configPath = configPath
        self.resourcePath = resourcePath
        self.userDictionaryPaths = userDictionaryPaths
    }

    

    
}

#if compiler(>=6)
extension TokenizerConfig: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeTokenizerConfig: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> TokenizerConfig {
        return
            try TokenizerConfig(
                dictionaryPath: FfiConverterString.read(from: &buf), 
                configPath: FfiConverterOptionString.read(from: &buf), 
                resourcePath: FfiConverterOptionString.read(from: &buf), 
                userDictionaryPaths: FfiConverterSequenceString.read(from: &buf)
        )
    }

    public static func write(_ value: TokenizerConfig, into buf: inout [UInt8]) {
        FfiConverterString.write(value.dictionaryPath, into: &buf)
        FfiConverterOptionString.write(value.configPath, into: &buf)
        FfiConverterOptionString.write(value.resourcePath, into: &buf)
        FfiConverterSequenceString.write(value.userDictionaryPaths, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTokenizerConfig_lift(_ buf: RustBuffer) throws -> TokenizerConfig {
    return try FfiConverterTypeTokenizerConfig.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTokenizerConfig_lower(_ value: TokenizerConfig) -> RustBuffer {
    return FfiConverterTypeTokenizerConfig.lower(value)
}


public enum SudachiError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    case DictionaryLoadError(message: String
    )
    case ConfigError(message: String
    )
    case TokenizeError(message: String
    )
    case InvalidArgument(message: String
    )

    

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension SudachiError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSudachiError: FfiConverterRustBuffer {
    typealias SwiftType = SudachiError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SudachiError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .DictionaryLoadError(
            message: try FfiConverterString.read(from: &buf)
            )
        case 2: return .ConfigError(
            message: try FfiConverterString.read(from: &buf)
            )
        case 3: return .TokenizeError(
            message: try FfiConverterString.read(from: &buf)
            )
        case 4: return .InvalidArgument(
            message: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: SudachiError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .DictionaryLoadError(message):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .ConfigError(message):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .TokenizeError(message):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .InvalidArgument(message):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(message, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSudachiError_lift(_ buf: RustBuffer) throws -> SudachiError {
    return try FfiConverterTypeSudachiError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSudachiError_lower(_ value: SudachiError) -> RustBuffer {
    return FfiConverterTypeSudachiError.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Tokenization granularity mode
 */

public enum TokenizeMode: Equatable, Hashable {
    
    /**
     * Short unit mode - maximum segmentation (equivalent to UniDic short unit)
     */
    case a
    /**
     * Middle unit mode - word-like segmentation
     */
    case b
    /**
     * Long unit mode - minimal segmentation, extracts named entities
     */
    case c





}

#if compiler(>=6)
extension TokenizeMode: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeTokenizeMode: FfiConverterRustBuffer {
    typealias SwiftType = TokenizeMode

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> TokenizeMode {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .a
        
        case 2: return .b
        
        case 3: return .c
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: TokenizeMode, into buf: inout [UInt8]) {
        switch value {
        
        
        case .a:
            writeInt(&buf, Int32(1))
        
        
        case .b:
            writeInt(&buf, Int32(2))
        
        
        case .c:
            writeInt(&buf, Int32(3))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTokenizeMode_lift(_ buf: RustBuffer) throws -> TokenizeMode {
    return try FfiConverterTypeTokenizeMode.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTokenizeMode_lower(_ value: TokenizeMode) -> RustBuffer {
    return FfiConverterTypeTokenizeMode.lower(value)
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterSequenceString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterSequenceString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceUInt32: FfiConverterRustBuffer {
    typealias SwiftType = [UInt32]

    public static func write(_ value: [UInt32], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterUInt32.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [UInt32] {
        let len: Int32 = try readInt(&buf)
        var seq = [UInt32]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterUInt32.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeMorphemeInfo: FfiConverterRustBuffer {
    typealias SwiftType = [MorphemeInfo]

    public static func write(_ value: [MorphemeInfo], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeMorphemeInfo.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [MorphemeInfo] {
        let len: Int32 = try readInt(&buf)
        var seq = [MorphemeInfo]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeMorphemeInfo.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeMorphemeWithSubunits: FfiConverterRustBuffer {
    typealias SwiftType = [MorphemeWithSubunits]

    public static func write(_ value: [MorphemeWithSubunits], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeMorphemeWithSubunits.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [MorphemeWithSubunits] {
        let len: Int32 = try readInt(&buf)
        var seq = [MorphemeWithSubunits]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeMorphemeWithSubunits.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeSentenceRange: FfiConverterRustBuffer {
    typealias SwiftType = [SentenceRange]

    public static func write(_ value: [SentenceRange], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeSentenceRange.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [SentenceRange] {
        let len: Int32 = try readInt(&buf)
        var seq = [SentenceRange]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeSentenceRange.read(from: &buf))
        }
        return seq
    }
}
/**
 * Get the library version
 */
public func getVersion() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_sudachi_swift_fn_func_get_version($0
    )
})
}
/**
 * Rule-based sentence splitter (no lexicon). For lexicon-aware splitting
 * use `Tokenizer.split_sentences` instead.
 */
public func splitSentences(text: String) -> [SentenceRange]  {
    return try!  FfiConverterSequenceTypeSentenceRange.lift(try! rustCall() {
    uniffi_sudachi_swift_fn_func_split_sentences(
        FfiConverterString.lower(text),$0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_sudachi_swift_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_sudachi_swift_checksum_func_get_version() != 831) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_sudachi_swift_checksum_func_split_sentences() != 34300) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_sudachi_swift_checksum_method_tokenizer_lookup() != 30566) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_sudachi_swift_checksum_method_tokenizer_pos_of() != 13682) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_sudachi_swift_checksum_method_tokenizer_split_sentences() != 59337) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_sudachi_swift_checksum_method_tokenizer_tokenize() != 14556) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_sudachi_swift_checksum_method_tokenizer_tokenize_with_subunits() != 62037) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_sudachi_swift_checksum_constructor_tokenizer_new() != 45939) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_sudachi_swift_checksum_constructor_tokenizer_with_dictionary() != 25173) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureSudachiSwiftInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all